### ISSUE TITLE
Erroneous "This installation is not using Cython" message

### ISSUE THREAD

**Issue by allie-tatarian** [nla-group/fABBA#4]
I am consistently receiving a "This installation is not using Cython" and "cython fail" message when I use fABBA, even though I do have Cython installed. I have Cython version 3.0.8 and fABBA version 1.1.2, installed both using pip, and both packages appear in the same directory on my machine.

I'm not sure if this is affecting how fABBA actually runs, but as I follow the example code in the documentation, sometimes I get the same output, but sometimes not.

**Comment by chenxinye** [comment]
Hi @allie-tatarian Thanks!.

For the Cython issue, some users reported before, most of them have this issue since their machine have firewall or without VC++ installed. Could you please provide your machine specifications for me?

I checked my three machines, all work properly. I guess you use Windows without VC++ installed?

I also posted the comment in our main review track.

**Comment by chenxinye** [comment]
Also @allie-tatarian  Do you install fABBA properly?

use ``pip install fABBA``

**Comment by allie-tatarian** [comment]
I wrote an update in the [JOSS thread](https://github.com/openjournals/joss-reviews/issues/6294#issuecomment-1924100290), but for completeness here: I think the issue is that my work computer's security/firewall was preventing Cython from working correctly. It may be helpful to add a note to [the docs](https://fabba.readthedocs.io/en/latest/quickstart.html) about the potential error message.
